import { Core } from "@strapi/strapi";
import { faker } from "@faker-js/faker";
import { PromisePool } from "@supercharge/promise-pool";

type ProductType = "BOOK";

// A type alias rather than an interface, so it is assignable to the JSON attribute.
type BookFilters = {
  /** Slugified genres, as generated by `faker.book.genre()`. */
  category?: string[];
  format?: ("HARDCOVER" | "TRADE_PAPERBACK" | "PAPERBACK")[];
  condition?: (
    | "NEW"
    | "PRISTINE"
    | "EXCELLENT"
    | "FINE"
    | "GOOD"
    | "FAIR"
    | "POOR"
  )[];
  /** Upper bound in cents, matching how SKU prices are stored. */
  maxPrice?: number;
  onSale?: boolean;
};

interface CatalogLandingPageSeed {
  title: string;
  summary?: string;
  productFilters: BookFilters;
}

type CatalogLandingPages = Record<
  ProductType,
  Record<string, CatalogLandingPageSeed>
>;

// Keyed by product type, then by slug.
const CATALOG_LANDING_PAGES = {
  BOOK: {
    fiction: {
      title: "Fiction",
      summary: "Novels and short stories from every corner of the imagination.",
      productFilters: {
        category: [
          "adventure",
          "classic",
          "drama",
          "fantasy",
          "historical-fiction",
          "horror",
          "mystery",
          "romance",
          "science-fiction",
          "thriller",
          "western",
        ],
      },
    },
    "non-fiction": {
      title: "Non-Fiction",
      summary: "Biographies, memoirs, and big ideas about the real world.",
      productFilters: {
        category: [
          "biography",
          "business",
          "memoir",
          "philosophy",
          "psychology",
          "religion",
        ],
      },
    },
    "mystery-thriller": {
      title: "Mystery & Thriller",
      summary: "Whodunits, detectives, and page-turners you won't put down.",
      productFilters: { category: ["mystery", "thriller", "detective"] },
    },
    "science-fiction-fantasy": {
      title: "Science Fiction & Fantasy",
      summary: "Distant futures, other worlds, and magic of every kind.",
      productFilters: { category: ["science-fiction", "fantasy"] },
    },
    romance: {
      title: "Romance",
      summary: "Love stories, from sweet to steamy.",
      productFilters: { category: ["romance"] },
    },
    hardcovers: {
      title: "Hardcovers",
      summary: "Durable, handsome editions built for the shelf.",
      productFilters: { format: ["HARDCOVER"] },
    },
    paperbacks: {
      title: "Paperbacks",
      summary: "Trade and mass-market paperbacks, light enough to take anywhere.",
      productFilters: { format: ["TRADE_PAPERBACK", "PAPERBACK"] },
    },
    "used-books": {
      title: "Used Books",
      summary: "Pre-loved copies at a fraction of the new price.",
      productFilters: {
        condition: ["PRISTINE", "EXCELLENT", "FINE", "GOOD", "FAIR", "POOR"],
      },
    },
    "like-new": {
      title: "Like New",
      summary: "Used copies in pristine or excellent condition.",
      productFilters: { condition: ["PRISTINE", "EXCELLENT"] },
    },
    "books-under-10": {
      title: "Books Under $10",
      summary: "Great reads that won't break the bank.",
      productFilters: { maxPrice: 1000 },
    },
    "bargain-paperbacks": {
      title: "Bargain Paperbacks",
      productFilters: { format: ["PAPERBACK"], maxPrice: 1000 },
    },
    "on-sale": {
      title: "On Sale",
      summary: "Limited-time discounts across the store.",
      productFilters: { onSale: true },
    },
  },
} satisfies CatalogLandingPages;

const FAKE_BOOK_PAGE_COUNT = 25;
const FAKE_FORMATS: NonNullable<BookFilters["format"]> = [
  "HARDCOVER",
  "TRADE_PAPERBACK",
  "PAPERBACK",
];
const FAKE_MAX_PRICES = [1000, 1500, 2000, 2500];
const CONCURRENCY = 5;

export async function seedCatalogLandingPages(
  strapi: Core.Strapi,
): Promise<void> {
  const landingPages = strapi.documents(
    "api::catalog-landing-page.catalog-landing-page",
  );
  if ((await landingPages.count({})) > 0) return;

  const catalog: CatalogLandingPages = {
    BOOK: {
      ...fakeBookLandingPages(
        FAKE_BOOK_PAGE_COUNT,
        Object.keys(CATALOG_LANDING_PAGES.BOOK),
      ),
      ...CATALOG_LANDING_PAGES.BOOK,
    },
  };

  const payloads = (
    Object.entries(catalog) as [ProductType, CatalogLandingPages[ProductType]][]
  ).flatMap(([productType, pages]) =>
    Object.entries(pages).map(([slug, { summary, ...page }]) => ({
      productType,
      slug,
      ...page,
      summary: summary ? toBlocks(summary) : undefined,
    })),
  );

  await PromisePool.withConcurrency(CONCURRENCY)
    .for(payloads)
    // The pool collects errors by default; rethrow so a failed insert aborts seeding.
    .handleError((error) => {
      throw error;
    })
    .process((data) => landingPages.create({ data, status: "published" }));
  strapi.log.info(`Seeded ${payloads.length} catalog landing pages`);
}

/** A plausible landing page slug, such as "gleaming-science-fiction". */
export function generateFakeSlug(genre = faker.book.genre()): string {
  return faker.helpers
    .slugify(`${faker.word.adjective()} ${genre}`)
    .toLowerCase();
}

/** Fake book landing pages, each filtering on one genre, keyed by a unique slug. */
function fakeBookLandingPages(
  count: number,
  takenSlugs: Iterable<string>,
): Record<string, CatalogLandingPageSeed> {
  const taken = new Set(takenSlugs);
  const pages: Record<string, CatalogLandingPageSeed> = {};

  while (Object.keys(pages).length < count) {
    const genre = faker.book.genre();
    const slug = generateFakeSlug(genre);
    if (taken.has(slug)) continue;
    taken.add(slug);

    pages[slug] = {
      title: titleFromSlug(slug),
      summary: faker.datatype.boolean({ probability: 0.8 })
        ? faker.lorem.sentences({ min: 1, max: 3 })
        : undefined,
      productFilters: {
        category: [faker.helpers.slugify(genre).toLowerCase()],
        // Some pages narrow the genre further, as a merchandiser might.
        format: faker.helpers.maybe(
          () => faker.helpers.arrayElements(FAKE_FORMATS, { min: 1, max: 2 }),
          { probability: 0.3 },
        ),
        maxPrice: faker.helpers.maybe(
          () => faker.helpers.arrayElement(FAKE_MAX_PRICES),
          { probability: 0.2 },
        ),
        onSale: faker.helpers.maybe(() => true, { probability: 0.1 }),
      },
    };
  }

  return pages;
}

function titleFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** Wraps plain text in the single paragraph a Strapi blocks field expects. */
function toBlocks(text: string) {
  return [
    {
      type: "paragraph" as const,
      children: [{ type: "text" as const, text }],
    },
  ];
}
