import { Core } from "@strapi/strapi";
import { faker } from "@faker-js/faker";
import { PromisePool } from "@supercharge/promise-pool";

type ProductType = "BOOK";

type CatalogEntity = "BOOK_CATEGORY" | ProductType;

// A type alias rather than an interface, so it is assignable to the JSON attribute.
type BookFilters = {
  /** Slugified genres, as generated by `faker.book.genre()`. */
  category?: string[];
  format?: ("HARDCOVER" | "TRADE_PAPERBACK" | "PAPERBACK")[];
  condition?: ("NEW" | "PRISTINE" | "EXCELLENT" | "GOOD" | "ACCEPTABLE")[];
  /** Upper bound in cents, matching how SKU prices are stored. */
  maxPrice?: number;
  onSale?: boolean;
};

/** Mirrors the `grid.grid` component, without its `__component` discriminator. */
interface Grid {
  entity: CatalogEntity;
  filters: BookFilters;
}

interface Catalog {
  title: string;
  summary?: string;
  layout: Grid[];
}

// Keyed by slug.
const CATALOGS = {
  fiction: {
    title: "Fiction",
    summary: "Novels and short stories from every corner of the imagination.",
    layout: bookGrid({
      category: [
        "adventure",
        "classic",
        "drama",
        "fantasy",
        "historical-fiction",
        "horror",
        "mystery",
        "romance",
        "science-fiction",
        "thriller",
        "western",
      ],
    }),
  },
  "non-fiction": {
    title: "Non-Fiction",
    summary: "Biographies, memoirs, and big ideas about the real world.",
    layout: bookGrid({
      category: [
        "biography",
        "business",
        "memoir",
        "philosophy",
        "psychology",
        "religion",
      ],
    }),
  },
  "mystery-thriller": {
    title: "Mystery & Thriller",
    summary: "Whodunits, detectives, and page-turners you won't put down.",
    layout: bookGrid({ category: ["mystery", "thriller", "detective"] }),
  },
  "science-fiction-fantasy": {
    title: "Science Fiction & Fantasy",
    summary: "Distant futures, other worlds, and magic of every kind.",
    layout: bookGrid({ category: ["science-fiction", "fantasy"] }),
  },
  romance: {
    title: "Romance",
    summary: "Love stories, from sweet to steamy.",
    layout: bookGrid({ category: ["romance"] }),
  },
  hardcovers: {
    title: "Hardcovers",
    summary: "Durable, handsome editions built for the shelf.",
    layout: bookGrid({ format: ["HARDCOVER"] }),
  },
  paperbacks: {
    title: "Paperbacks",
    summary: "Trade and mass-market paperbacks, light enough to take anywhere.",
    layout: bookGrid({ format: ["TRADE_PAPERBACK", "PAPERBACK"] }),
  },
  "used-books": {
    title: "Used Books",
    summary: "Pre-loved copies at a fraction of the new price.",
    layout: bookGrid({
      condition: ["PRISTINE", "EXCELLENT", "GOOD", "ACCEPTABLE"],
    }),
  },
  "like-new": {
    title: "Like New",
    summary: "Used copies in pristine or excellent condition.",
    layout: bookGrid({ condition: ["PRISTINE", "EXCELLENT"] }),
  },
  "books-under-10": {
    title: "Books Under $10",
    summary: "Great reads that won't break the bank.",
    layout: bookGrid({ maxPrice: 1000 }),
  },
  "bargain-paperbacks": {
    title: "Bargain Paperbacks",
    layout: bookGrid({ format: ["PAPERBACK"], maxPrice: 1000 }),
  },
  "on-sale": {
    title: "On Sale",
    summary: "Limited-time discounts across the store.",
    layout: bookGrid({ onSale: true }),
  },
  genre: {
    title: "Genres",
    layout: [{ entity: "BOOK_CATEGORY", filters: {} }],
  },
} satisfies Record<string, Catalog>;

const FAKE_BOOK_PAGE_COUNT = 25;
const FAKE_FORMATS: NonNullable<BookFilters["format"]> = [
  "HARDCOVER",
  "TRADE_PAPERBACK",
  "PAPERBACK",
];
const FAKE_MAX_PRICES = [1000, 1500, 2000, 2500];
const CONCURRENCY = 5;

export async function seedCatalogs(strapi: Core.Strapi): Promise<void> {
  const catalogs = strapi.documents("api::catalog.catalog");
  if ((await catalogs.count({})) > 0) {
    strapi.log.info("Catalogs have already been seeded");
    return;
  }

  const genres = genreCatalogs();
  const pages: Record<string, Catalog> = {
    ...fakeBookCatalog(FAKE_BOOK_PAGE_COUNT, [
      ...Object.keys(genres),
      ...Object.keys(CATALOGS),
    ]),
    // Curated pages win a slug clash, e.g. "romance" keeps its summary.
    ...genres,
    ...CATALOGS,
  };

  const payloads = Object.entries(pages).map(
    ([slug, { summary, layout, ...page }]) => ({
      urlPath: catalogUrlPath(slug),
      ...page,
      summary: summary ? toBlocks(summary) : undefined,
      layout: layout.map((grid) => ({
        __component: "grid.grid" as const,
        ...grid,
      })),
    }),
  );

  await PromisePool.withConcurrency(CONCURRENCY)
    .for(payloads)
    // The pool collects errors by default; rethrow so a failed insert aborts seeding.
    .handleError((error) => {
      throw error;
    })
    .process((data) => catalogs.create({ data, status: "published" }));
  strapi.log.info(`Seeded ${payloads.length} catalogs`);
}

function catalogUrlPath(slug: string): string {
  return `/books/${slug}/`;
}

/** The slug of a genre's own catalog, which is also its value in category filters. */
function genreSlug(genre: string): string {
  return faker.helpers.slugify(genre).toLowerCase();
}

/** The URL path of a genre's own catalog. */
export function genreUrlPath(genre: string): string {
  return catalogUrlPath(genreSlug(genre));
}

/** A single grid listing the books that match `filters`. */
function bookGrid(filters: BookFilters): Grid[] {
  return [{ entity: "BOOK", filters }];
}

/**
 * One catalog per genre `faker.book.genre()` can produce, titled after the genre,
 * so every book category has a landing page to link to.
 */
function genreCatalogs(): Record<string, Catalog> {
  return Object.fromEntries(
    faker.definitions.book.genre.map((genre) => [
      genreSlug(genre),
      { title: genre, layout: bookGrid({ category: [genreSlug(genre)] }) },
    ]),
  );
}

/** A plausible landing page slug, such as "gleaming-science-fiction". */
export function generateFakeSlug(genre = faker.book.genre()): string {
  return faker.helpers
    .slugify(`${faker.word.adjective()} ${genre}`)
    .toLowerCase();
}

/** Fake book landing pages, each filtering on one genre, keyed by a unique slug. */
function fakeBookCatalog(
  count: number,
  takenSlugs: Iterable<string>,
): Record<string, Catalog> {
  const taken = new Set(takenSlugs);
  const pages: Record<string, Catalog> = {};

  while (Object.keys(pages).length < count) {
    const genre = faker.book.genre();
    const slug = generateFakeSlug(genre);
    if (taken.has(slug)) continue;
    taken.add(slug);

    pages[slug] = {
      title: titleFromSlug(slug),
      summary: faker.datatype.boolean({ probability: 0.8 })
        ? faker.lorem.sentences({ min: 1, max: 3 })
        : undefined,
      layout: bookGrid({
        category: [genreSlug(genre)],
        // Some pages narrow the genre further, as a merchandiser might.
        format: faker.helpers.maybe(
          () => faker.helpers.arrayElements(FAKE_FORMATS, { min: 1, max: 2 }),
          { probability: 0.3 },
        ),
        maxPrice: faker.helpers.maybe(
          () => faker.helpers.arrayElement(FAKE_MAX_PRICES),
          { probability: 0.2 },
        ),
        onSale: faker.helpers.maybe(() => true, { probability: 0.1 }),
      }),
    };
  }

  return pages;
}

function titleFromSlug(slug: string): string {
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

/** Wraps plain text in the single paragraph a Strapi blocks field expects. */
function toBlocks(text: string) {
  return [
    {
      type: "paragraph" as const,
      children: [{ type: "text" as const, text }],
    },
  ];
}
